import '../database.dart';

class DisciplinaryRecordsTable extends SupabaseTable<DisciplinaryRecordsRow> {
  @override
  String get tableName => 'disciplinary_records';

  @override
  DisciplinaryRecordsRow createRow(Map<String, dynamic> data) =>
      DisciplinaryRecordsRow(data);
}

class DisciplinaryRecordsRow extends SupabaseDataRow {
  DisciplinaryRecordsRow(Map<String, dynamic> data) : super(data);

  @override
  SupabaseTable get table => DisciplinaryRecordsTable();

  String get id => getField<String>('id')!;
  set id(String value) => setField<String>('id', value);

  String get staffId => getField<String>('staff_id')!;
  set staffId(String value) => setField<String>('staff_id', value);

  String get disciplineType => getField<String>('discipline_type')!;
  set disciplineType(String value) =>
      setField<String>('discipline_type', value);

  String get reason => getField<String>('reason')!;
  set reason(String value) => setField<String>('reason', value);

  String? get description => getField<String>('description');
  set description(String? value) => setField<String>('description', value);

  List<String> get evidenceDocumentIds =>
      getListField<String>('evidence_document_ids');
  set evidenceDocumentIds(List<String>? value) =>
      setListField<String>('evidence_document_ids', value);

  String? get evidenceNotes => getField<String>('evidence_notes');
  set evidenceNotes(String? value) => setField<String>('evidence_notes', value);

  bool? get autoGenerated => getField<bool>('auto_generated');
  set autoGenerated(bool? value) => setField<bool>('auto_generated', value);

  String? get triggerRule => getField<String>('trigger_rule');
  set triggerRule(String? value) => setField<String>('trigger_rule', value);

  dynamic get triggerData => getField<dynamic>('trigger_data');
  set triggerData(dynamic value) => setField<dynamic>('trigger_data', value);

  String? get issuedBy => getField<String>('issued_by');
  set issuedBy(String? value) => setField<String>('issued_by', value);

  DateTime get issuedAt => getField<DateTime>('issued_at')!;
  set issuedAt(DateTime value) => setField<DateTime>('issued_at', value);

  bool? get acknowledged => getField<bool>('acknowledged');
  set acknowledged(bool? value) => setField<bool>('acknowledged', value);

  DateTime? get acknowledgedAt => getField<DateTime>('acknowledged_at');
  set acknowledgedAt(DateTime? value) =>
      setField<DateTime>('acknowledged_at', value);

  String? get acknowledgmentNotes => getField<String>('acknowledgment_notes');
  set acknowledgmentNotes(String? value) =>
      setField<String>('acknowledgment_notes', value);

  bool? get appealSubmitted => getField<bool>('appeal_submitted');
  set appealSubmitted(bool? value) => setField<bool>('appeal_submitted', value);

  DateTime? get appealDate => getField<DateTime>('appeal_date');
  set appealDate(DateTime? value) => setField<DateTime>('appeal_date', value);

  String? get appealText => getField<String>('appeal_text');
  set appealText(String? value) => setField<String>('appeal_text', value);

  List<String> get appealEvidenceIds =>
      getListField<String>('appeal_evidence_ids');
  set appealEvidenceIds(List<String>? value) =>
      setListField<String>('appeal_evidence_ids', value);

  String? get appealStatus => getField<String>('appeal_status');
  set appealStatus(String? value) => setField<String>('appeal_status', value);

  String? get appealDecision => getField<String>('appeal_decision');
  set appealDecision(String? value) =>
      setField<String>('appeal_decision', value);

  String? get appealDecidedBy => getField<String>('appeal_decided_by');
  set appealDecidedBy(String? value) =>
      setField<String>('appeal_decided_by', value);

  DateTime? get appealDecidedAt => getField<DateTime>('appeal_decided_at');
  set appealDecidedAt(DateTime? value) =>
      setField<DateTime>('appeal_decided_at', value);

  DateTime? get expiresAt => getField<DateTime>('expires_at');
  set expiresAt(DateTime? value) => setField<DateTime>('expires_at', value);

  bool? get isActive => getField<bool>('is_active');
  set isActive(bool? value) => setField<bool>('is_active', value);

  DateTime get createdAt => getField<DateTime>('created_at')!;
  set createdAt(DateTime value) => setField<DateTime>('created_at', value);

  DateTime get updatedAt => getField<DateTime>('updated_at')!;
  set updatedAt(DateTime value) => setField<DateTime>('updated_at', value);
}
