import '../database.dart';

class ZArchivePerfAlertsTable extends SupabaseTable<ZArchivePerfAlertsRow> {
  @override
  String get tableName => 'z_archive_perf_alerts';

  @override
  ZArchivePerfAlertsRow createRow(Map<String, dynamic> data) =>
      ZArchivePerfAlertsRow(data);
}

class ZArchivePerfAlertsRow extends SupabaseDataRow {
  ZArchivePerfAlertsRow(Map<String, dynamic> data) : super(data);

  @override
  SupabaseTable get table => ZArchivePerfAlertsTable();

  String get id => getField<String>('id')!;
  set id(String value) => setField<String>('id', value);

  String get alertType => getField<String>('alert_type')!;
  set alertType(String value) => setField<String>('alert_type', value);

  String get metricName => getField<String>('metric_name')!;
  set metricName(String value) => setField<String>('metric_name', value);

  double get thresholdValue => getField<double>('threshold_value')!;
  set thresholdValue(double value) =>
      setField<double>('threshold_value', value);

  double get actualValue => getField<double>('actual_value')!;
  set actualValue(double value) => setField<double>('actual_value', value);

  String get message => getField<String>('message')!;
  set message(String value) => setField<String>('message', value);

  int? get severity => getField<int>('severity');
  set severity(int? value) => setField<int>('severity', value);

  bool? get acknowledged => getField<bool>('acknowledged');
  set acknowledged(bool? value) => setField<bool>('acknowledged', value);

  String? get acknowledgedBy => getField<String>('acknowledged_by');
  set acknowledgedBy(String? value) =>
      setField<String>('acknowledged_by', value);

  DateTime? get acknowledgedAt => getField<DateTime>('acknowledged_at');
  set acknowledgedAt(DateTime? value) =>
      setField<DateTime>('acknowledged_at', value);

  bool? get resolved => getField<bool>('resolved');
  set resolved(bool? value) => setField<bool>('resolved', value);

  String? get resolvedBy => getField<String>('resolved_by');
  set resolvedBy(String? value) => setField<String>('resolved_by', value);

  DateTime? get resolvedAt => getField<DateTime>('resolved_at');
  set resolvedAt(DateTime? value) => setField<DateTime>('resolved_at', value);

  bool? get autoGenerated => getField<bool>('auto_generated');
  set autoGenerated(bool? value) => setField<bool>('auto_generated', value);

  DateTime get createdAt => getField<DateTime>('created_at')!;
  set createdAt(DateTime value) => setField<DateTime>('created_at', value);

  DateTime get updatedAt => getField<DateTime>('updated_at')!;
  set updatedAt(DateTime value) => setField<DateTime>('updated_at', value);
}
